@startuml
!define table(x) class x << (T,#FFEEEE) >>

package "Bucket: sensors" {
  table(temperature) {
    + _measurement: string [PK]
    + _time: timestamp [PK]
    --
    + mold_id: tag
    + group_id: tag
    + position: tag
    + status: tag
    --
    + temperature: float
    + threshold: float
    + deviation: float
    + delta_T_calcaire: float
    + epaisseur_mm: float
  }

  table(flow) {
    + _measurement: string [PK]
    + _time: timestamp [PK]
    --
    + group_id: tag
    + unit: tag
    --
    + flow_rate: float
  }
}

note top of temperature
  tags : mold_id={1|2}
         group_id={1..4}
         position={gauche|droite}
         status={OK|ALERTE|CRITIQUE}
  fields: temperature(1déc.)
          delta_T_calcaire(2déc.)
          epaisseur_mm(2déc.)
end note

note top of flow
  tags: group_id={1..4}
        unit="lpm"
  field: flow_rate(2déc.)
end note

temperature ||--o{ temperature : "6 points / cycle\n(6 capteurs)"
@enduml
